### PR TITLE
add MPT past-kv shape for TSModelForCausal class

### PR DESCRIPTION
**Pull request by changwangss**
# What does this PR do?
this PR is used to support generate [mosaicml/mpt-7b-chat](https://huggingface.co/mosaicml/mpt-7b-chat) past-kv shape, please check and review. @echarlaix 
here is the related PR in optimum,[#1101](https://github.com/huggingface/optimum/pull/1101) merged.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by hshen14 — APPROVED** [review]
LGTM

**Comment by hshen14** [comment]
@echarlaix Please review the PR. Thanks.

**Review by PenghuiCheng — APPROVED** [review]

**Review by echarlaix — COMMENTED** [review]
LGTM, thanks for the addition ! Could you add a test for mpt models before we merge ?

**Comment by changwangss** [comment]
> LGTM, thanks for the addition ! Could you add a test for mpt models before we merge ?

May I use this model as UT? it seems the little large, https://huggingface.co/mosaicml/mpt-7b-chat/tree/main, Could you help me create a tiny model if need?

**Comment by echarlaix** [comment]
> > LGTM, thanks for the addition ! Could you add a test for mpt models before we merge ?
> 
> May I use this model as UT? it seems the little large, https://huggingface.co/mosaicml/mpt-7b-chat/tree/main, Could you help me create a tiny model if need?

Tiny models now available under the [hf-internal-testing](https://huggingface.co/hf-internal-testing/tiny-random-MptForCausalLM) organization

**Comment by changwangss** [comment]
close PR, because mpt PR merged to transformers, we can reuse the origin code to generate the correct past key values shape.

**Comment by changwangss** [comment]
close PR, because mpt PR merged to transformers, we can reuse the origin code to generate the correct past key values shape.

**Pull request closed without merging**
