### PR TITLE
Fix openvino main export

### PR DESCRIPTION
**Pull request by echarlaix**
Fix `main_export` for decoder models (which were exported twice  : with /without past) as well as the resulting model file name which where wrongfully set for single models (SD and encoder/decoder models were not concerned).  Also now the different `OVModelForXxx` classes all use `main_export` to export the model when needed

### CODE REVIEW

**Comment by helena-intel** [comment]
Thanks Ella!  I noticed one issue with CausalLM export: when loading the model, I got the error "use_cache` was set to `True` but the loaded model only supports `use_cache=False". During export I saw `Overriding 2 configuration item(s) - use_cache -> True` but it appears the model is exported without cache.

**Comment by echarlaix** [comment]
> Thanks Ella! I noticed one issue with CausalLM export: when loading the model, I got the error "use_cache`was set to`True`but the loaded model only supports`use_cache=False". During export I saw `Overriding 2 configuration item(s) - use_cache -> True` but it appears the model is exported without cache.

Thanks a lot for reporting it @helena-intel, could you share a code snippet for me to reproduce this ?

**Comment by echarlaix** [comment]
cc @eaidova

**Comment by helena-intel** [comment]
> Thanks a lot for reporting it @helena-intel, could you share a code snippet for me to reproduce this ?

When I tried to reproduce it it did not occur, so I suppose it was a strange thing in my environment. Sorry for the false alarm!

**Review by helena-intel — APPROVED** [review]

**Comment by echarlaix** [comment]
> When I tried to reproduce it it did not occur, so I suppose it was a strange thing in my environment. Sorry for the false alarm!

Thanks a lot for checking @helena-intel

**Pull request merged**
