### PR TITLE
Symbol use in optimum: fix misprint

### PR DESCRIPTION
**Pull request by jane-intel**
# What does this PR do?
This PR fixes a misprint critical for optimum symbol use. Without it, the feature couldn't work properly.

@echarlaix, @eaidova

## Before submitting
- [N/A] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [N/A] Did you make sure to update the documentation with your changes?
- [N/A] Did you write any new necessary tests?

### CODE REVIEW

**Review by eaidova — APPROVED** [review]

**Comment by eaidova** [comment]
@echarlaix  @IlyasMoutawwakil could you please trigger precommit, thanks

**Review by echarlaix — APPROVED** [review]

**Comment by eaidova** [comment]
@echarlaix  @IlyasMoutawwakil  could you please help to retrigger precommit?

**Comment by IlyasMoutawwakil** [comment]
there seem to be some failures are they related to this change ?

**Comment by IlyasMoutawwakil** [comment]
I might be mistaken but this one seems related no ?
```
FAILED tests/openvino/test_modeling.py::OVModelForCausalLMIntegrationTest::test_compare_to_transformers_35_glm4 - RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:245:
Exception from src/bindings/python/src/pyopenvino/core/infer_request.hpp:54:
Caught exception: Exception from src/plugins/intel_cpu/src/node.cpp:593:
[CPU] Concat node with name 'aten::cat/Concat' Check 'TRShape::merge_into(output_shape, in_copy)' failed at src/core/shape_inference/include/concat_shape_inference.hpp:43:
While validating node 'opset1::Concat aten::cat/Concat (opset1::Reshape aten::flatten/Reshape[0]:f32[?,4,?,4], opset1::VariadicSplit VariadicSplit_18980331[1]:f32[?,4,?,4]) -> (f32[?,4,?,8])' with friendly_name 'aten::cat/Concat':
Shape inference input shapes {{6,4,11,4},{6,4,1,4}}
Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 3).
```

**Comment by eaidova** [comment]
> I might be mistaken but this one seems related no ?
> 
> ```
> FAILED tests/openvino/test_modeling.py::OVModelForCausalLMIntegrationTest::test_compare_to_transformers_35_glm4 - RuntimeError: Exception from src/inference/src/cpp/infer_request.cpp:245:
> Exception from src/bindings/python/src/pyopenvino/core/infer_request.hpp:54:
> Caught exception: Exception from src/plugins/intel_cpu/src/node.cpp:593:
> [CPU] Concat node with name 'aten::cat/Concat' Check 'TRShape::merge_into(output_shape, in_copy)' failed at src/core/shape_inference/include/concat_shape_inference.hpp:43:
> While validating node 'opset1::Concat aten::cat/Concat (opset1::Reshape aten::flatten/Reshape[0]:f32[?,4,?,4], opset1::VariadicSplit VariadicSplit_18980331[1]:f32[?,4,?,4]) -> (f32[?,4,?,8])' with friendly_name 'aten::cat/Concat':
> Shape inference input shapes {{6,4,11,4},{6,4,1,4}}
> Argument shapes are inconsistent; they must have the same rank, and must have equal dimension everywhere except on the concatenation axis (axis 3).
> ```

@IlyasMoutawwakil  that is not related to @jane-intel changes, but her provided improvement highlighted an issue with postion_ids processing in OVModelForCausalLM for models from glm models family. I fixed that as part of this PR.

**Comment by jane-intel** [comment]
@eaidova thank you for fixing `tests/openvino/test_modeling.py::OVModelForCausalLMIntegrationTest::test_compare_to_transformers_35_glm4`

Other failures are unrelated to this PR. @IlyasMoutawwakil, @echarlaix please preceded with merge

**Review by IlyasMoutawwakil — APPROVED** [review]

**Pull request merged**
