### PR TITLE
Added config for Phi-3-mini-4k-instruct

### PR DESCRIPTION
**Pull request by MaximProshin**
# What does this PR do?

Added compression config for microsoft/Phi-3-mini-4k-instruct.

### CODE REVIEW

**Comment by MaximProshin** [comment]
@AlexKoff88 , please review. cc @KodiaqQ @ljaljushkin

**Review by AlexKoff88 — APPROVED** [review]

**Review by KodiaqQ — APPROVED** [review]

**Comment by echarlaix** [comment]
Not related to this PR but looks like a lot of tests are now failing since the latest openvino release, could someone from the openvino team take a look @AlexKoff88 ? In the meantime, we can still restrict the openvino version wdyt ?

**Comment by AlexKoff88** [comment]
> Not related to this PR but looks like a lot of tests are now failing since the latest openvino release, could someone from the openvino team take a look @AlexKoff88 ? In the meantime, we can still restrict the openvino version wdyt ?

Thanks, @echarlaix. There are some issues but we will make it green.

**Comment by echarlaix** [comment]
> Thanks, @echarlaix. There are some issues but we will make it green.

Thanks a lot !

**Pull request merged**
