### PR TITLE
rm ipex inference

### PR DESCRIPTION
**Pull request by jiqing-feng**
The `inference_mode` of ipex should be removed early in v1.18.0

### CODE REVIEW

**Comment by jiqing-feng** [comment]
It will fix the error check of #823

**Review by echarlaix — APPROVED** [review]

**Comment by jiqing-feng** [comment]
Hi @echarlaix @IlyasMoutawwakil , would you please help to trigger the tests? Thx!

**Comment by echarlaix** [comment]
cc @mfuntowicz

**Comment by jiqing-feng** [comment]
Hi @mfuntowicz . Do you have any concerns about it? We are going to remove `inference_mode` in optimum-intel.

**Comment by jiqing-feng** [comment]
Hi @mfuntowicz . Do you mind taking a look at this PR? Thx.

**Pull request merged**
