### PR TITLE
Fixed issues in the Hybrid quantization notebook

### PR DESCRIPTION
**Pull request by AlexKoff88**

### CODE REVIEW

**Comment by AlexKoff88** [comment]
@l-bat, please take a look, ASAP.

**Review by l-bat — APPROVED** [review]
Minor comment: I think the output in the `Quantize the Model` section should be removed to improve readability

**Review by echarlaix — APPROVED** [review]

**Comment by echarlaix** [comment]
@AlexKoff88 feel free to merge once ready

**Comment by AlexKoff88** [comment]
@helena-intel, just fyi, I've fixed a couple of issues in the notebook you contributed some time ago. It is just about `trust_remote_code` flag.

**Pull request merged**
