### PR TITLE
allow to use SDPA in clip models

### PR DESCRIPTION
**Pull request by eaidova**
# What does this PR do?

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Review by AlexKoff88 — APPROVED** [review]

**Review by echarlaix — COMMENTED** [review]
Thanks @eaidova ! Opened https://github.com/huggingface/optimum/pull/2066 to remove `CLIPModelPatcher` direclty in optimum (shouldn't be needed for onnx), would that works for you ?

**Comment by eaidova** [comment]
> Thanks @eaidova ! Opened [huggingface/optimum#2066](https://github.com/huggingface/optimum/pull/2066) to remove `CLIPModelPatcher` direclty in optimum (shouldn't be needed for onnx), would that works for you ?

@echarlaix  thanks, but are you sure that it is not need? as I understand @IlyasMoutawwakil met integration issue for onnx export that is why it was added

**Comment by echarlaix** [comment]
> @echarlaix thanks, but are you sure that it is not need? as I understand @IlyasMoutawwakil met integration issue for onnx export that is why it was added

Actually might be needed for diffusers model, let's merge this PR for now and we can always revert changes if updated in optimum

**Review by echarlaix — APPROVED** [review]

**Comment by IlyasMoutawwakil** [comment]
the specific onnx error was https://github.com/pytorch/pytorch/issues/135615 and it was fixed in latest pytorch https://github.com/pytorch/pytorch/issues/135615

**Pull request merged**
