### PR TITLE
refine Dockerfile to support both cpu and xpu platform

### PR DESCRIPTION
**Pull request by kaixuanliu**

### CODE REVIEW

**Comment by kaixuanliu** [comment]
@echarlaix , Can you help review? Thx.

**Comment by IlyasMoutawwakil** [comment]
There's a CI workflow that tests building the image, can you update it as well ?

**Comment by kaixuanliu** [comment]
Oh, yes. have fixed it.

**Comment by helena-intel** [comment]
If this Dockerfile in the is specificially for IPEX, should it be renamed to Dockerfile.ipex, to not confuse users?

**Comment by kaixuanliu** [comment]
@helena-intel ,Hi, this Dockerfile is just used for CI test, but I think your advice is OK. Have renamed it to `Dockerfile.ipex`

**Comment by IlyasMoutawwakil** [comment]
Hi ! I aslo think having separate Docker files is better. The build test is failing tho

**Comment by kaixuanliu** [comment]
Seems there is sth wrong with access to machine putting release wheel files. Have replaced --extra-index-url from `https://pytorch-extension.intel.com/release-whl/stable/cpu/us/` to `https://pytorch-extension.intel.com/release-whl/stable/cpu/cn/` temporarily

**Pull request merged**
