### PR TITLE
Prepare to NNCF v2.5 release

### PR DESCRIPTION
**Pull request by ljaljushkin**
# What does this PR do?

This PR updates deprecate NNCF API calls for switching to the upcoming NNCF 2.5.0 release.
The `.forward` on the NNCFNetwork function will always be an NNCF-wrapped forward version, no need to call `get_nncf_wrapped_model`

The API changes were introduced in the https://github.com/openvinotoolkit/nncf/pull/1584

### CODE REVIEW

**Comment by ljaljushkin** [comment]
@vshampor @AlexKoff88 @yujiepan-work @vuiseng9 please take a look

**Comment by yujiepan-work** [comment]
This can solve https://github.com/huggingface/optimum-intel/issues/313

**Review by vshampor — APPROVED** [review]

**Comment by helena-intel** [comment]
Thanks for this @ljaljushkin ! When is the NNCF 2.5 release planned? This should not be merged before that, because with `pip install optimum-intel[openvino,nncf]` users will get 2.4 at the moment. We should also update setup.py to update the nncf extra to "nncf>=2.5.0".

**Comment by ljaljushkin** [comment]
> 

Thanks, Helena! Added nncf 2.5.0 to setup.py. AFAIK, the plan was to release at the same time as openvino 2023.0

**Review by echarlaix — APPROVED** [review]
LGTM, thanks for this addition @ljaljushkin ! Will merge it once nncf v2.5.0 release is out

**Comment by helena-intel** [comment]
@echarlaix NNCF 2.5 is released! https://github.com/openvinotoolkit/nncf/releases/tag/v2.5.0

**Pull request merged**
