### PR TITLE
Update quantized_generation_demo.ipynb

### PR DESCRIPTION
**Pull request by dnoliver**
Fix version of torch to 2.0.1. 
See https://github.com/pytorch/pytorch/issues/125109

# What does this PR do?

Running this notebook with current pytorch version fails.
Test Platform: Windows 11 - Intel Core Ultra 7 165HL
Error Message: `OSError: [WinError 126] ... Error loading "C:\Users\xyz\AppData\Roaming\Python\Python312\site-packages\torch\lib\shm.dll" or one of its dependencies.`
Applying the recommendation in https://github.com/pytorch/pytorch/issues/125109, and rolling back the version to 2.0.1

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by eaidova** [comment]
@dnoliver is it really necessary to use such old pytorch? As I can see in issue, downgrade on 2.2 should be enough

**Comment by dnoliver** [comment]
Will try with 2.2.2 and update you!

**Comment by dnoliver** [comment]
Run into an error in further cells:

image

The stack trace is:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[10], line 7
      4 # Tokenize the sample
      5 inputs = tokenizer([sample], return_tensors='pt')    
----> 7 out = stateless_model.generate(
      8     **inputs,
      9     max_new_tokens=128,
     10     streamer=TextStreamer(tokenizer=tokenizer, skip_special_tokens=True),
     11     pad_token_id=tokenizer.eos_token_id,
     12     prompt_lookup_num_tokens=3,
     13 )    

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\torch\utils\_contextlib.py:115, in context_decorator.<locals>.decorate_context(*args, **kwargs)
    112 @functools.wraps(func)
    113 def decorate_context(*args, **kwargs):
    114     with ctx_factory():
--> 115         return func(*args, **kwargs)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\generation\utils.py:1559, in GenerationMixin.generate(self, inputs, generation_config, logits_processor, stopping_criteria, prefix_allowed_tokens_fn, synced_gpus, assistant_model, streamer, negative_prompt_ids, negative_prompt_attention_mask, **kwargs)
   1549     candidate_generator = self._get_candidate_generator(
   1550         generation_config=generation_config,
   1551         input_ids=input_ids,
   (...)
   1555         model_kwargs=model_kwargs,
...
Eltwise shape infer input shapes dim index: 3 mismatch
```

**Comment by dnoliver** [comment]
@eaidova we were using this notebook to validate a Meteor Lake system that we later found that it had bad drivers for NPU and GPU.

We have validated it in another device, with good drivers, Windows 11, works fine:

image

**Comment by eaidova** [comment]
@dnoliver great, I also tested your notebook, it is also working for me. Should we put some message about proper driver version requirements to install (e.g. refer on this page for NPU https://docs.openvino.ai/2024/get-started/configurations/configurations-intel-npu.html)?

**Comment by dnoliver** [comment]
This is how a healthy system looks like:
- Display Adapters => Intel(R) Arc(TM) Graphics is healthy
- Neural Processors => Intel(R) AI Boost is healthy

image

And this is how an unhealthy system looks like:
- Both devices have a warning sign, and reporting error 43 in the Device Status.

image

The referenced documentation for the NPU is not accurate for Windows. In the docs it says "the NPU is most likely listed in “Other devices” as “Multimedia Video Controller.”", but it is in "Neural Processors". Other than that, installing latest drivers' versions should address most issues

**Pull request merged**
