### PR TITLE
Improve INC CI test torch version

### PR DESCRIPTION
**Pull request by changwangss**
# What does this PR do?

INC and INC IPEX are currently maintaining torch 2.4 and 2.5 but the CI have torch 2.2 and 2.3, which caused errors.

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by changwangss** [comment]
All INC CI passed, Could you please take a look about the IPEX issue? @jiqing-feng

**Comment by jiqing-feng** [comment]
The error brings by #975

**Comment by IlyasMoutawwakil** [comment]
when was the backward compatibility broken ? is there a table somewhere that we can link to for users to downgrade inc for torch>2.3 ?

**Comment by jiqing-feng** [comment]
> when was the backward compatibility broken ? is there a table somewhere that we can link to for users to downgrade inc for torch>2.3 ?

Hi Llyas, I think you can just ignore the failed tests in IPEX because we are refactoring the IPEXModel, in our new architecture, all ipex tests passed. So you can just review #1009

**Comment by IlyasMoutawwakil** [comment]
> The error brings by https://github.com/huggingface/optimum-intel/pull/975

the pr you're mentioning only robustified the CI to make sure we're testing specific torch/ipex versions. no ipex modeling files were changed.

**Comment by jiqing-feng** [comment]
> > The error brings by #975
> 
> the pr you're mentioning only robustified the CI to make sure we're testing specific torch/ipex versions. no ipex modeling files were changed.

I see, there are some errors when upgrading torch to 2.4 in the current IPEXModel, but we are all fixed in #1009

**Comment by IlyasMoutawwakil** [comment]
okay ! let's add the version pinning in #1009

**Comment by jiqing-feng** [comment]
> okay ! let's add the version pinning in #1009

And please merge this PR, it's just for upgrading torch version of INC CI

**Pull request merged**
