### PR TITLE
fix deprecated arg shared_memory

### PR DESCRIPTION
**Pull request by sanbuphy**
# What does this PR do?

fix deprecated arg shared_memory

Fixes # (issue)

## Before submitting
- [ ] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

### CODE REVIEW

**Comment by sanbuphy** [comment]
@jiwaszki   could you take a look ?  thank you :)

**Review by jiwaszki — APPROVED** [review]
Thanks @sanbuphy !

@echarlaix can you trigger CIs? Thank you in advance!

**Comment by jiwaszki** [comment]
@sanbuphy BTW do you have free time to experiment with my older PR https://github.com/huggingface/optimum-intel/pull/429 ?
It needs to be refreshed. Overall the goal is to introduce `share_outputs` flags correctly into the pipelines without loosing data in the meantime. Maybe there are cases where copy can be omitted, it needs a little bit of exploration.
Would you like to do it as well? (separate PR ofc)

**Comment by sanbuphy** [comment]
> @sanbuphy BTW do you have free time to experiment with my older PR #429 ? It needs to be refreshed. Overall the goal is to introduce `share_outputs` flags correctly into the pipelines without loosing data in the meantime. Maybe there are cases where copy can be omitted, it needs a little bit of exploration. Would you like to do it as well? (separate PR ofc)

Sorry,  could you descripe   `Overall the goal is to introduce share_outputs flags correctly into the pipelines without loosing data in the meantime. Maybe there are cases where copy can be omitted` more detail ?  i'm not sure about the meaning of ` into the pipelines without loosing data in the meantime` and `there are cases where copy can be omitted`  ; what should i do to profile this ?  btw do you have discord ?  maybe we can talk about this in that

**Comment by jiwaszki** [comment]
@sanbuphy sure, you can find me on [Intel DevHub server](https://discord.gg/wPuqAujS) or by my username `jiwaszki_23704`.

**Review by echarlaix — APPROVED** [review]
LGTM, thanks @sanbuphy !

**Pull request merged**
